apiVersion: v2
name: pet-battle
description: A Helm chart to deploy the frontend of the Pet Battle
type: application
version: 1.0.0
appVersion: "1.2.2"
home: https://springdo.github.io/pet-battle
maintainers:
  - name: springdo
  - name: eformat
