app_name: pet-battle
replicas: 1
# build info not used atm
build:
  enabled: false
  build_tag: latest
  source_docker_file_path: Dockerfile
  # source_context_dir: "/"
  # source_ref: master
  # source_repo: https://github.com/springdo/pet-battle.git
# Docker deets
image_repository: quay.io
image_name: pet-battle
image_namespace: petbattle
# likely over written by the Argo definition
app_tag: latest

# OCP route
route: true
# custom end point injected by config map. This is likely to changed
config_map: '{
  "catsUrl": "http://pet-battle-api-labs-dev.apps.hivec.sandbox1254.opentlc.com",
  "tournamentsUrl": "http://pet-battle-tournament-labs-dev.apps.hivec.sandbox1254.opentlc.com",
  "keycloak": {
    "issuer": "https://keycloak-labs-dev.apps.hivec.sandbox1254.opentlc.com/auth/realms/pbrealm",
    "redirectUri": "http://pb-pet-battle-mickey-mouse.apps.hivec.sandbox1254.opentlc.com/tournament",
    "clientId": "pbclient",
    "responseType": "code",
    "scope": "openid profile email",
    "requireHttps": false,
    "showDebugInformation": true,
    "disableAtHashCheck": true
  }
}'
