app_name: pet-battle
replicas: 1
# build info not used atm
build:
  enabled: false
  build_tag: latest
  source_docker_file_path: Dockerfile
  # source_context_dir: "/"
  # source_ref: master
  # source_repo: https://github.com/springdo/pet-battle.git
# Docker deets
image_repository: quay.io
image_name: pet-battle
image_namespace: petbattle
# likely over written by the Argo definition
app_tag: latest
a_b_deploy:
  weight: 100
  # svc_name:

# OCP route
route: true
# custom end point injected by config map. This is likely to changed
config_map: '{
  "catsUrl": "http://pet-battle-api-labs-test.apps.hivec.sandbox1459.opentlc.com",
  "tournamentsUrl": "http://pet-battle-tournament-labs-test.apps.hivec.sandbox1459.opentlc.com",
  "keycloak": {
    "url": "https://keycloak-labs-test.apps.hivec.sandbox1293.opentlc.com/auth/",
    "realm": "pbrealm",
    "clientId": "pbclient",
    "redirectUri": "http://localhost:4200/tournament",
    "enableLogging": true
  }
}'
