app_name: pet-battle
replicas: 1
# build info not used atm
build:
  enabled: false
  build_tag: latest
  source_docker_file_path: Dockerfile
  # source_context_dir: "/"
  # source_ref: master
  # source_repo: https://github.com/springdo/pet-battle.git
# Docker deets
image_repository: quay.io
image_name: pet-battle
image_namespace: springdo
# likely over written by the Argo definition
app_tag: latest

# OCP route
route: true
# custom end point injected by config map. This is likely to changed
config_map: '{
  "catUrl": "http://pet-battle-api-labs-staging.apps.hivec.sandbox1438.opentlc.com",
  "apiUrl": "http://pet-battle-tournament-labs-staging.apps.hivec.sandbox1438.opentlc.com",
  "keycloak": {
    "issuer": "http://localhost:8080/auth/realms/pbrealm",
    "redirectUri": "http://localhost:4200/",
    "clientId": "pbclient",
    "responseType": "code",
    "scope": "openid profile email",
    "requireHttps": false,
    "showDebugInformation": true,
    "disableAtHashCheck": true
  }
}'
