---
apiVersion: v1
kind: Namespace
metadata:
  name: staging-pb-subs
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-pb-subs
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: staging-placementrule
  namespace: staging-pb-subs
  generation: 1
  labels:
    purpose: staging-pb-subs
spec:
  clusterLabels:
    matchLabels:
      env: staging
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prod-placementrule
  namespace: prod-pb-subs
  generation: 1
  labels:
    purpose: prod-pb-subs
spec:
  clusterLabels:
    matchLabels:
      env: prod
