---
apiVersion: v1
kind: Namespace
metadata:
  name: staging-pb-subs
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-pb-subs
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    purpose: prod-pb-subs
  name: pet-battle
  namespace: prod-pb-subs
  annotations:
spec:
  channel: pet-battle-ch/nexus-charts
  name: pet-battle
  packageOverrides:
    - packageName: pet-battle
      packageOverrides:
        - path: spec
          value:
            config_map: "'http://blah-bl2ah.apps.c100-e.eu-gb.containers.cloud.ibm.com'"
  packageFilter:
    version: '1.0.0'
  placement:
    placementRef:
      name: prod-placementrule
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    purpose: staging-pb-subs
    app: pet-battle-staging
  name: staging-pet-battle
  namespace: staging-pb-subs
  annotations:
spec:
  channel: pet-battle-ch/nexus-charts
  name: pet-battle
  packageOverrides:
    - packageName: pet-battle
      packageOverrides:
        - path: spec
          value:
            config_map: "'http://blah-blah.apps.demo-app-cluster.walkersdev.co.uk'"
  packageFilter:
    version: '>1.0.0'
  placement:
    placementRef:
      name: staging-placementrule
      kind: PlacementRule
