{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "pet-battle.fullname" . }}
  labels:
    {{- include "pet-battle.labels" . | nindent 4 }}
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {{ include "pet-battle.fullname" . }}
    weight: 100
  wildcardPolicy: None
  {{- if .Values.a_b_deploy.svc_name }}
  alternateBackends:
  - kind: Service
    name: {{ .Values.a_b_deploy.svc_name }}
    weight: {{ .Values.a_b_deploy.weight }}
  {{- end }}
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
{{ end }}
