{{- if .Values.config_map }}
---
kind: ConfigMap
data:
  env: |-
    (function (window) {
      window.__env = window.__env || {};
      window.__env.customEnv = {{ .Values.config_map }}
      // Whether or not to enable debug mode
      // Setting this to false will disable console output
      window.__env.enableDebug = true;
    }(this));
metadata:
  name: environment
  namespace: {{ .Values.destination_namespace }}
{{- end }}