---
apiVersion: v1
kind: Namespace
metadata:
  name: pet-battle-ch
spec:
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: nexus-charts
  namespace: pet-battle-ch
spec:
  type: HelmRepo
  pathname: https://dschromeos.github.io/pet-battle/
