app_name: pet-battle

# build info not used atm
source_repo: https://github.com/springdo/pet-battle.git
build_tag: 
source_context_dir: "/"

# Docker deets
image_repository: quay.io
image_name: pet-battle
image_namespace: springdo
# likely over written by the Argo definition
app_tag: latest

# OCP route
route: true

# custom end point injected by config map. This is likely to changed
config_map: "'http://cats-pet-battle-api.apps.s43.core.rht-labs.com'"
