---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: staging-placementrule
  namespace: staging-pb-subs
  generation: 1
  labels:
    purpose: staging-pb-subs
spec:
  clusterConditions:
    - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      env: 'staging'
      cloud: 'Amazon'
  clusterReplicas: 1
