---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pet-battle-api
  namespace: staging-pb-subs
spec:
  selector:
    matchExpressions:
      - key: purpose
        operator: In
        values:
          - staging-pb-subs
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
